name: Docker's implementation of CIS Docker Benchmarks
description: Assumes you have built or pulled an image into Docker for security benchmarking. 
inputs:
  image-name:
    description: The name of the Docker image, without the label. Assuming is that you have already built or pulled the image
    required: true
runs:
  using: 'composite'
  steps:
    - name: Download Docker Bench for Security
      uses: actions/checkout@v3
      with:
        repository: 'docker/docker-bench-security'
        path: 'docker-bench-security'

    - name: Run Docker Bench for Security
      id: run-docker-benchmark
      env:
        DOCKER_CONTENT_TRUST: 1
        IMAGE_NAME: ubuntu
      working-directory: ./docker-bench-security
      run: |
        docker info
        chmod +x docker-bench-security.sh
        ls -la 
        ./docker-bench-security.sh -c container_images -i ${{ inputs.image-name }}
        echo "Debug: Contents of docker-bench-security.log.json:"
        cat ./log/docker-bench-security.log.json
        total_checks=$(jq '.checks' ./log/docker-bench-security.log.json)
        current_score=$(jq '.score' ./log/docker-bench-security.log.json)
        echo "total_checks=$total_checks" >> $GITHUB_ENV
        echo "current_score=$current_score" >> $GITHUB_ENV
        echo "### Docker Benchmark for Security" >> $GITHUB_STEP_SUMMARY
        echo "Checks: $total_checks." >> $GITHUB_STEP_SUMMARY
        echo "Score: $current_score." >> $GITHUB_STEP_SUMMARY
      shell: bash
      
    - name: Run Docker Bench Security
      run: |
        docker run --rm \
          -v "${{ github.workspace }}/docker-bench-security/docker-bench-security.sh:/docker-bench-security.sh" \
          --workdir / \
          ${{ inputs.image-name }} \
          /bin/sh -c "chmod +x /docker-bench-security.sh && /docker-bench-security.sh -c container_images -i ${{ inputs.image-name }}"
      shell: bash

    - name: Fail if Docker Benchmark did not make checks
      if: ${{ env.total_checks == '0' }}
      run: |
        echo "Docker Benchmark did not appear to make any checks. Verify that the parameters used with docker-bench-security.sh are correct."
        exit 1
      shell: bash

    - name: Fail if Docker Benchmark score is too low
      if: ${{ env.current_score < 0 }}
      run: |
        echo "Docker Benchmark has scored your image as ${{ env.current_score }}. Raise the score to at least 0."
        exit 1
      shell: bash