name: Docker's implementation of CIS Docker Benchmarks
description: Assumes you have built or pulled an image into Docker for security benchmarking. 
inputs:
  image-name:
    description: the name of the Docker image, without the label. Assuming is that you have alrady build or pulled the image
    required: true
runs:
  using: "composite"
  steps:
    - name: Download Docker benck for security
      uses: action/checkout@v3
      with:
        repository: docker/docker-bench-security
        path: docker-bench-security

    - name: Run Docker bench for security
      id: run-docker-benchmark
      working-directory: ./docker-bench-security
      run: |
        ./docker-bench-security.sh -c container_images -i ${{ inputs.image-name }}
        total_checks=$(jq '.checks' ./log/docker-bench-security.log.json)
        current_score=$(jq '.checks' ./log/docker-bench-security.log.json)
        echo "total_checks=$total_checks" >> $GITHUB_OUTPUT
        echo "current_score=$tcurrent_score" >> $GITHUB_OUTPUT
        echo "### Docker Benchmark for security" >> $GITHUB_STEP_SUMMARY
        echo "Checks: $total_checks." >> $GITHUB_STEP_SUMMARY
        echo "Score: $current_score." >> $GITHUB_STEP_SUMMARY
      shell: bash

    - name: Fail if Docker Benchmark did not make checks
      if: ${{ steps.run-docker-benchmark.outputs.total_checks == 0 }}
      run: |
        echo "Docker Benchmark did not appear to make any checks. Verrify that the parameters used with docker-bench-security.sh are correct."
        exit 1
      shell: bash

    - name: Fail if Docker Benchmark score is too low
      if: ${{ steps.run-docker-benchmark.outputs.total_checks < 0 }}
      run: |
        echo "Docker Benchmark has scored your image as ${{ steps.run-docker-benchmark.outputs.current_score }}. Raise the score to at least 0."
        exit 1
      shell: bash