name: Test Image Size Action

on: [push, pull_request]

jobs:
  test-image-size:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: pull image
        run: docker pull mcr.microsoft.com/openjdk/jdk:21-ubuntu

      - name: Test Image Size Action
        uses: ./container-image-size
        with:
          build-image: mcr.microsoft.com/openjdk/jdk:21-ubuntu
          base-image: ubuntu:latest
